name: flutter_application_1
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.16.2 <=3.3.4'
dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    provider: ^6.0.0

    # plugin necessary for projet
    flutter_bloc: ^8.1.1
    connectivity_plus: ^2.3.9
    equatable: ^2.0.5
    shared_preferences: ^2.0.15
    http: ^0.13.5
    dio: ^4.0.6
    flutter_launcher_icons: ^0.10.0
    flutter_native_splash: ^2.2.11
    
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0
flutter:
    uses-material-design: true


  # To add assets to your application, add an assets section, like this:
    assets:
        - assets/
        - assets/images/
        - assets/icons/
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages